### ISSUE TITLE
Setting SESAME_MAX_AGE ––> ValueError at /  not enough values to unpack (expected 2, got 1) 

### ISSUE THREAD

**Issue by Hukkinen** [aaugustin/django-sesame#16]
In signing.py, in class TimestampSigner, in function unsign, on the line 188, which is:
 
        value, timestamp = result.rsplit(self.sep, 1)

**Comment by aaugustin** [comment]
If I understand correctly:

- you left SESAME_MAX_AGE unset (it defaults to None)
- you generated some tokens
- then you set SESAME_MAX_AGE to a value other than None
- the tokens cause this error

Is that correct?

The current implementation can only process tokens generated with the same settings.

Perhaps the error handling could be improved there, probably by logging the problem and failing authentication rather than crashing.
