### ISSUE TITLE
[Inquiry] Useable without passwords?

### ISSUE THREAD

**Issue by estianross** [aaugustin/django-sesame#34]
I see it supports custom user models, provided they have password field, what if this field NEVER has a value set? We **completely** disregard the password field in our current implementation but it still exists on our custom user model, will this result in duplicate tokens? I see it's specified that by default, sesame's tokens don't expire but are tied to the password of the user with changing the password invalidating the token, how would this impact our system if we were to switch from our custom passwordless system (simple short lived generated code sent via email and passed back via urlparam)?

**Comment by aaugustin** [comment]
Yes, if all user passwords are set to `None`, everyone would have the same token in this scenario.

**Comment by aaugustin** [comment]
I think the easiest solution would be to call `set_unusable_password()` on every user.

**Comment by estianross** [comment]
Thanks for confirming my suspicions and suggesting a possible solution

**Comment by aaugustin** [comment]
Upon further investigation, this doesn't result in duplicate tokens because the user's PK is included in the token and is part of the signature. I'm committing a test that demonstrates this.

I answered too quickly yesterday. I assumed by mistake that only the revocation key was signed. Thankfully not, because that would have been a nasty security issue in some scenarios.
