### ISSUE TITLE
SESAME_PRIMARY_KEY_FIELD=uuid does not allow login

### ISSUE THREAD

**Issue by hendrikschneider** [aaugustin/django-sesame#95]
Hello,

I have a custom user model with the regular id as primary key and also an uuid field. I saw the setting `SESAME_PRIMARY_KEY_FIELD` and wanted to set it to "uuid" so that the user uuid is being stored with sesame and not the integer primary key. 

Unfortunately, the login then always fails. In the moment, I remove the settings, it works.

```
SESAME_TOKEN_NAME = "sesame"
SESAME_MAX_AGE = timedelta(days=10)
SESAME_PRIMARY_KEY_FIELD = "uuid" # Having this one enabled -> Logins do not work
SESAME_TOKENS = ["sesame.tokens_v2"]
```

**Comment by aaugustin** [comment]
Your bug report boils down to "it doesn't work". A setup matching exactly your description works for me. That makes it hard to help you, all the more since you can look at your code and I can't.

Did you check logs? What do they say?
https://django-sesame.readthedocs.io/en/stable/faq.html#how-do-i-understand-why-a-token-is-invalid

**Comment by hendrikschneider** [comment]
@aaugustin Thank you for your quick answer!

It seems that django's login function is the issue here. I will try to debug it more to solve it.
