### ISSUE TITLE
Add an option to invalidate magic links on email change

### ISSUE THREAD

**Issue by tianyishan** [aaugustin/django-sesame#96]
Hi there,

I have noticed that your library has a useful option INVALIDATE_ON_PASSWORD_CHANGE that invalidates magic links when a user changes their password (tokens_v2.py). This is a great security feature.

I would like to suggest adding a similar option to invalidate magic links when a user changes their email address. This could be called INVALIDATE_ON_EMAIL_CHANGE. Implementing this feature would help ensure that any previously issued magic links associated with the old email address become invalid, preventing unauthorized access to the account using outdated links. This can be particularly important if the user's previous email address has been compromised or is no longer under their control.

Adding this option can further enhance the security and functionality of your library. I believe it would be a valuable addition to the available features. Please let me know your thoughts on this suggestion, and if you need any help implementing this change, I would be happy to contribute.

Thank you for your consideration!

**Comment by aaugustin** [comment]
In the current version of django-sesame, the recommended way to achieve this is to use the email address as the [token scope](https://django-sesame.readthedocs.io/en/stable/howto.html#scoped-tokens).

It would be technically possible to implement an `INVALIDATE_ON_EMAIL_CHANGE` setting, which would default to `False` for backwards compatibility and crash if the User model doesn't provide an email field, designated by [get_email_field_name](https://docs.djangoproject.com/en/4.2/topics/auth/customizing/#django.contrib.auth.models.AbstractBaseUser.get_email_field_name).

This isn't currently implemented because django-sesame requires AbstractBaseUser, nothing more, and that base class [doesn't define an email field](https://github.com/django/django/blob/3b62d8c83e3e48d2ed61cfa32a61c56d9e030293/django/contrib/auth/base_user.py#L57-L59).

**Comment by aaugustin** [comment]
#97 implements this feature request.

I'm not clear on typical scenarios where this would mitigate a security issue. As a consequence, the docs are a bit fuzzy.

@adamchainz Do you have an opinion on whether it would make sense to add this feature? Or is the use case too narrow?

**Comment by aaugustin** [comment]
Version 3.2, which includes this feature, is available on PyPI.
